### ISSUE TITLE
Add Github Org Link 

### ISSUE THREAD

**Issue by gtalarico** [aecworks/aec.works-web#38]
Somewhere on the page we should include a link to our github org to help communicate its open source! And so people can report bugs, etc

Maybe on navbar? 
Or maybe one of those corner ribbon looking things (meh)? Or maybe we need a footer?

Thoughts @aecworks/aecworks-frontend-devs?

**Comment by daneyul** [comment]
I was thinking a footer might be good to have in general. But then the question is how do you get to the footer if the main content scrolls endlessly.
I think next to the 'login' button on the nav would be a logical place. The right side of the nav can be for CTAs.
<img width="761" alt="Screen Shot 2020-10-02 at 21 41 02" src="https://user-images.githubusercontent.com/21328582/94924245-23906c00-04f8-11eb-8819-826a26096f0d.png">

**Comment by m-clare** [comment]
You can also have it as a sticky footer that would sit at the bottom right corner even with scrolling. Trying to find an example, but I've seen that kind of thing, with it being pretty unobstrusive (just like a chip with "this project is open source!")

**Comment by gtalarico** [comment]
Ps: have you try to get to the footer on dev.to?
On pages with infinite scrolling it shows up for a and then slips away when new content reloads

**Comment by danrocha** [comment]
or we could stop infinite scrolling and add a "Load more" link, right before the footer 😬
https://www.nngroup.com/articles/infinite-scrolling/

**Comment by daneyul** [comment]
Oh yeah, a sticky footer as @m-clare suggested could be cool. Or even a sticky something in the bottom corner, like a floating button.

<img width="335" alt="Screen Shot 2020-10-04 at 10 42 11" src="https://user-images.githubusercontent.com/21328582/95005048-43c24700-062e-11eb-93b9-cb7fd887af04.png">


Regarding the infinite scrolling, what if the company list had an overflow on the scroll? Like maybe show a few companies and then the feed will scroll in its own container.

I was also wondering if the companies feed wants to show the list at a macro level. If the list of companies grows, it might be a bit arduous to scroll through the long list one by one. Perhaps giving an option to display a more condensed version? or a grid of companies with less detail?

**Comment by m-clare** [comment]
You could also do expansion panels with maybe the company name and favicon/logo + website?

**Comment by gtalarico** [comment]
Lot's of good ideas here and topics to capture:

## Github Link / Footer
Might be helpful to review the overall UI organization:
* Upper nav bar is for main content sections
* Upper right is user, login, settings, etc.
* Sidebar is nav for the active content -search, filter, etc

I think it could go next to "login" as @daneyul suggested, but we might want to plan for what else is missing -
We are missing a place for Github link, Twitter link, and maybe a link to "about project or community" etc. 
Anything else?

Could be a footer, but could also be a small floating tab, against the edge, or maybe bottom of sidebar.
If footer, could be sticky or at bottom.  
Main down side of footer, if fixed, uses valuable vertical screen space - this is especially problematic on mobile.

Thoughts?

Here are some sketches to help guide the conversation:

### 1
![image](https://user-images.githubusercontent.com/9513968/95005708-d91ef600-05b0-11eb-9e31-ac170ecbb293.png)

### 2
![image](https://user-images.githubusercontent.com/9513968/95005721-de7c4080-05b0-11eb-8bcf-88fdad9a5433.png)

### 3
![image](https://user-images.githubusercontent.com/9513968/95005735-e6d47b80-05b0-11eb-989e-b4156ced389b.png)


## Scrolling Behaviour
@danrocha that article raises some good points about downsides. 
This particularly resonated with me:
> Endless scrolling is not recommended for goal-oriented finding tasks

In a way, it seems like it should **not** be used in "companies", as user might be "on a mission" to find something, task-like.
But you could argue it is the right interaction for the feed, which is more of an unlimited consumption type of content.
But we probably also want some consistency!

I am ok with switching over to a "load more" type of interaction as long as it feels sleek and nice to use.
Any examples that are elegant and maybe even fun?
Maybe a nice animation from the bottom pops up when you reach the bottom with a button to click?

**Comment by daneyul** [comment]
Hard to say unless we draft up a few sketches on figma with the actual icons and links and stuff, but they all seem like logical places to put the “about” content

**Comment by danrocha** [comment]
If we leave infinite scrolling on, I would definitely go for option 1. I actually thought this was what dev.to did, until I saw your comment and tried to scroll it all the way to the bottom, and saw a flash of a footer! 

I did a quick search, here are some examples of sites that do it in an _okay_-way:

- Discourse → it has an extra scrollbar to indicate where you are in the discussion: https://discuss.emberjs.com/t/ember-cli-the-ramcat-way/7666/13
- http://scrollsample.appspot.com/items → coming from a [HN discussion](https://news.ycombinator.com/item?id=7314965), seems to be an "in-between" solution
- http://tangent128.name/depot/toys/freefall/freefall-flytable.html#1 → it updates the URL as you scroll, allowing you to go back and forth with your browser and not 
- Same here: https://snapguide.com/guides/
- Same here, is a slightly different way: https://tumbledry.org/2011/05/12/screw_hashbangs_building  ([HN discussion](https://news.ycombinator.com/item?id=2592741))
- Basecamp also uses a JS library to keep history in place in their IS feed: https://m.signalvnoise.com/snapback-cache---what-we-use-to-make-our-infinite-scrolling-feeds-at-highrise-awesome/

For me, the issues with IS outweight its benefits. Looking at some scenarios:

- I am scrolling through an "endless" list of companies, find a company interesting, click on its link to see the page, then hit back on my browser, only to have completely lost my position in the endless page
- I am scrolling through an "endless" list because I remember I saw something there previously, but do not quite remeber at which level down, so I just keep scrolling until I find it (which in a paginated system we would have a slight idea, "oh, it was somewhere after some page clicks")
- I am scrolling through an endless list on my chromebook or my not so powerful phone, and the browser starts to lag because all of the scrolled companies are stored in memory as they load, and after some hundreds of companies, the scrolling becomes unusable
- I am holding the scrollbar and scrolling down cos the list is big, but the scrollbar keeps jumping under my mouse because of IS constantly changing the page length
- I have disabilities and use a screen reader to go through the list; all the problems above would probably make me completely lost within the site

It is worth notin that a lot of the above is solvable with good JS or CSS hacks, as shown in some of the examples above :)

**Comment by daneyul** [comment]
Unrelated to infinite scrolling, but I made a page on the [figma file](https://www.figma.com/file/vMZLnv9mWjS0lhpKMtugOU/aec.works?node-id=532%3A25) for the social icons. Kinda diggin' the icons on the side. I saw that the [Canny blog](https://canny.io/blog/) has side icons too. Feel free to add onto it and make changes.

**Comment by gtalarico** [comment]
That looks good to me @daneyul 

I am good with any of those, although the sep. button ones could be nice to animate a slide out with text on hover, to clarify target:
![image](https://user-images.githubusercontent.com/9513968/95123293-91aa7e00-0706-11eb-88ac-6647549a9766.png)


We can just hide it on mobile for now, or slide it down, maybe with no sliding effect? Or... ?
![image](https://user-images.githubusercontent.com/9513968/95123310-9a02b900-0706-11eb-9b73-d97fd8b1170d.png)

**Comment by gtalarico** [comment]
closed via #51 , thanks @daneyul !
